
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[257] =
    {   0,
        2,    2,   19,   18,    2,    1,   17,   10,    5,   17,
       17,    2,   16,   17,   17,   17,    7,   17,   13,    6,
       17,   17,   17,   12,   17,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       17,    2,    0,    2,   17,    0,   10,   15,   10,   10,
       10,   10,   10,    0,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    5,   17,   17,    2,   11,    0,   11,
       11,    2,   11,   11,   11,    0,   11,   11,   11,   11,
       11,    0,   11,    0,   11,   11,   11,   11,   17,   13,
        0,    3,   13,   13,    9,   17,   12,   12,   12,   12,

       12,   12,   12,    8,   12,   12,   12,   12,   12,   12,
        8,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   11,   11,   11,   14,
       11,   11,    2,   11,   11,   11,   11,   11,   11,   11,
       11,   11,    0,    0,    0,    0,    0,    0,    0,    0,
       11,   11,    0,    0,    0,    3,   13,    9,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,    8,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   10,   10,   10,   11,

       11,   14,   11,    4,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   10,   11,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       10,   11,   12,   12,   12,   12,   12,   12,   12,   10,
       11,   12,   12,   12,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   25,   40,   41,   42,   43,
       44,   45,   25,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    3,    1,    1,    3,    3,    4,    5,
        5,    3,    3,    1,    3,    6,    7,    8,    1,    1,
        3,    3,    3,    1,    8,    1,    1,    1,    3,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    3,    1
    } ;

static const flex_int16_t yy_base[266] =
    {   0,
        0,    0,  584,  585,   56,   61,  561,   70,    0,  560,
      573,  126,  585,  558,   47,  130,  561,  169,  167,  585,
       46,  556,  114,    0,  585,  528,  530,  156,  149,  147,
      148,  531,  159,  530,  538,  158,  519,  528,  526,  531,
      512,  202,  562,    0,  585,  561,  543,  559,  541,  554,
      539,  188,  193,  198,  538,  543,  191,  536,  195,  201,
        0,  518,  494,    0,  585,  585,  218,  252,  538,  305,
      124,  220,    0,  532,  522,  513,    0,  262,  203,  508,
      235,  513,  358,  406,  497,  453,  189,  239,  585,  261,
      260,    0,  264,  267,    0,  585,    0,  463,  473,  460,

      475,  462,  468,  454,  455,  452,  451,  454,  451,  448,
        0,  447,  451,   25,  449,  239,  255,  453,  446,  249,
      248,  451,  467,  466,  479,  278,  275,  468,  467,  281,
      282,  468,    0,  444,  427,  424,  276,  457,  439,  585,
      455,  132,  322,  460,  457,  244,  288,  293,  307,  451,
        0,  425,  454,  450,  449,  446,  444,  442,  441,  439,
      393,  285,  434,  330,  428,    0,  319,    0,  400,  412,
      405,  393,  291,  405,  403,  399,  391,  397,  400,    0,
      386,  392,  389,  378,  380,  382,  389,  375,  373,  373,
      385,  375,  379,  383,  385,  372,  327,  328,  377,  331,

      332,  585,  376,  585,  370,  361,  369,  358,  365,  358,
      355,  355,  355,  352,  364,  354,  358,  363,  362,  360,
      350,  355,  343,  355,  345,  344,  343,  344,  349,  340,
      334,  335,  343,  336,  336,  320,  326,  328,  317,  320,
      322,  321,  307,  307,  316,    0,  304,  301,  291,    0,
        0,  284,  270,  277,  259,  585,  509,  512,  222,  520,
      526,  532,  540,  548,  206
    } ;

static const flex_int16_t yy_def[266] =
    {   0,
      256,    1,  256,  256,  256,  256,  256,  256,  257,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  258,  256,
      256,  256,  256,  259,  256,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      256,  256,  260,   12,  256,  260,    8,  260,    8,    8,
        8,    8,    8,  260,    8,    8,    8,    8,    8,    8,
        8,   60,    8,  257,  256,  256,  256,  261,  256,  261,
       70,  256,   70,   70,   70,  256,   70,   70,   70,   70,
       70,  256,  262,  256,   70,  262,   86,   70,  256,  258,
      263,  264,  258,  258,  265,  256,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,    8,    8,    8,    8,    8,    8,    8,    8,
        8,   60,   60,   60,   60,    8,   70,   70,   86,  256,
       70,   70,  256,   70,   70,   70,   70,   70,   70,   86,
       86,   86,  256,  256,  256,  256,  256,  256,  256,  256,
       86,   70,  263,  263,  256,  264,  258,  265,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,    8,    8,   60,   70,

       70,  256,   86,  256,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,   60,   86,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
       60,   86,  259,  259,  259,  259,  259,  259,  259,   60,
       86,  259,  259,  259,  259,    0,  256,  256,  256,  256,
      256,  256,  256,  256,  256
    } ;

static const flex_int16_t yy_nxt[643] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   13,   16,   17,   18,   19,   20,   13,
       21,   22,   23,    4,   24,   13,    4,   13,   25,   24,
       26,   27,   28,   29,   30,   31,   32,   24,   33,   24,
       34,   24,   24,   24,   24,   35,   36,   37,   38,   39,
       40,   24,   24,   24,   13,   41,   13,   42,   42,   89,
       43,  183,   42,   42,   44,   43,   96,   45,   65,   44,
       46,   46,  184,   47,   48,   46,   49,   50,   46,   46,
       46,   51,   52,   46,   53,   54,   55,   56,   46,   46,
       57,   58,   59,   46,   60,   46,   46,   46,   61,   60,

       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   62,   60,   60,   60,
       60,   60,   60,   60,   46,   63,   46,   67,   67,   68,
       69,  142,   70,   71,   72,   45,   96,   73,   74,  142,
       75,   76,   77,   78,   89,   80,   79,   80,   81,   82,
       83,   65,   84,   80,   85,   86,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   87,   83,   83,   83,   83,   83,   83,   83,
       91,   88,   93,  103,   94,   92,  100,  105,  108,  106,
       65,  109,  104,  101,  111,  115,  116,  140,  107,  102,

      126,  112,   48,   42,   42,  117,   43,  127,  118,  124,
       44,  130,  123,  168,  124,  128,  123,  131,  132,   67,
       67,   67,   67,  148,  138,  133,   67,  161,  143,   97,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  134,  133,  133,
      133,  133,  133,  133,  133,   68,  138,  149,   70,   71,
       80,  200,  164,   73,   74,   80,   75,   76,   77,  137,
      140,  165,   79,  138,   81,  186,  256,  147,   90,  256,
       85,  167,   93,   80,   94,  188,  194,  192,  195,  127,
      126,  147,  187,  111,  162,  193,  124,   80,  139,  124,

      189,  130,  123,  123,  131,  201,   80,   88,   68,   80,
      111,   70,   71,  148,  138,  180,   73,   74,  180,   75,
       76,   77,  137,   67,   67,   79,  141,   81,  138,  149,
       67,  255,  164,   85,  256,  254,  167,  206,  207,  180,
      162,  165,  129,  129,  197,  198,  147,  147,  200,  201,
      253,  139,   80,   80,  111,  252,  251,  250,  249,  248,
       88,   68,  247,  180,   70,   71,  140,  180,  111,   73,
       74,  246,   75,   76,   77,  150,  180,  180,   79,   80,
       81,  245,  180,  180,  244,  243,   85,  242,  241,  111,
      240,  239,  180,  238,  237,  236,  235,  234,  233,  111,

      232,  231,  111,  230,  152,  229,  228,  227,  111,  180,
      226,  225,  224,   88,  140,  223,  111,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  180,  111,
      211,  210,  180,  180,  209,  208,  153,  154,  180,  180,
      155,  156,  205,  180,  204,  165,  203,  140,  157,  140,
      140,  158,  202,  159,  140,  160,   68,  140,  140,   70,
       71,  256,  140,  161,   73,   74,  147,   75,   76,   77,
      150,  145,  144,   79,   80,   81,  138,  161,  138,  136,
      199,   85,  135,  129,  198,  197,  125,  123,  123,  196,
      191,  190,  185,  182,  180,  181,  180,  179,  178,  152,

      177,  176,  175,  174,  173,  172,  171,  170,   88,   64,
      169,   64,   64,   64,   64,   64,   64,   95,   80,   95,
       46,  140,   46,   46,   46,   46,   46,   46,   86,  138,
      146,   86,   86,   86,  151,  151,  145,  151,  151,  151,
      163,  163,  163,  163,  144,  163,  140,  163,  166,  136,
      166,  166,  166,  166,  166,  166,  135,  123,  129,  124,
      124,  125,  124,   48,  123,   48,   48,   66,  122,  121,
      120,  119,  114,  113,  110,   99,   98,   45,   90,   65,
       66,   65,   45,  256,    3,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256
    } ;

static const flex_int16_t yy_chk[643] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,   15,
        5,  114,    6,    6,    5,    6,   21,   21,   15,    6,
        8,    8,  114,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,   12,   12,   12,
       12,   71,   12,   12,   12,   23,   23,   12,   12,  142,
       12,   12,   12,   12,   16,   71,   12,   12,   12,   12,
       12,   16,   12,  142,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       18,   12,   19,   29,   19,   18,   28,   30,   31,   30,
       18,   31,   29,   28,   33,   36,   36,   87,   30,   28,

       52,   33,   54,   42,   42,   36,   42,   53,   36,   52,
       42,   57,   57,  265,   53,   54,   59,   59,   60,   67,
       67,   72,   72,   79,   79,   60,   67,   87,   72,  259,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   68,   81,   81,   68,   68,
       88,  146,   91,   68,   68,  146,   68,   68,   68,   68,
       78,   91,   68,   68,   68,  116,   90,   78,   90,   93,
       68,   93,   94,   78,   94,  117,  121,  120,  121,  127,
      126,  137,  116,  255,   88,  120,  127,  137,   68,  126,

      117,  130,  130,  131,  131,  147,  162,   68,   70,  147,
      254,   70,   70,  148,  148,  253,   70,   70,  252,   70,
       70,   70,   70,  143,  143,   70,   70,   70,  149,  149,
      143,  249,  164,   70,  167,  248,  167,  173,  173,  247,
      162,  164,  197,  198,  197,  198,  200,  201,  200,  201,
      245,   70,  200,  201,  244,  243,  242,  241,  240,  239,
       70,   83,  238,  237,   83,   83,   83,  236,  235,   83,
       83,  234,   83,   83,   83,   83,  233,  232,   83,   83,
       83,  231,  230,  229,  228,  227,   83,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,

      213,  212,  211,  210,   83,  209,  208,  207,  206,  205,
      203,  199,  196,   83,   84,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      179,  178,  177,  176,  175,  174,   84,   84,  172,  171,
       84,   84,  170,  169,  165,  163,  161,  160,   84,  159,
      158,   84,  157,   84,  156,   84,   86,  155,  154,   86,
       86,   86,  153,  152,   86,   86,  150,   86,   86,   86,
       86,  145,  144,   86,   86,   86,  141,  139,  138,  136,
      135,   86,  134,  132,  129,  128,  125,  124,  123,  122,
      119,  118,  115,  113,  112,  110,  109,  108,  107,   86,

      106,  105,  104,  103,  102,  101,  100,   99,   86,  257,
       98,  257,  257,  257,  257,  257,  257,  258,   85,  258,
      260,   82,  260,  260,  260,  260,  260,  260,  261,   80,
       76,  261,  261,  261,  262,  262,   75,  262,  262,  262,
      263,  263,  263,  263,   74,  263,   69,  263,  264,   63,
      264,  264,  264,  264,  264,  264,   62,   58,   56,   55,
       51,   50,   49,   48,   47,   46,   43,   41,   40,   39,
       38,   37,   35,   34,   32,   27,   26,   22,   17,   14,
       11,   10,    7,    3,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
    #include<stdio.h>
    #include<string.h>
	#include"y.tab.h"
	const int INT_MAX = 1 << 30;
	int cur_scope;
	int params_cnt;
	int funccall_params_cnt;

    struct symbol_table {
        char type[100];
        char name[100];
		char Class[100];
		char value[100];
		int line_number;
        int valid;
		int scope;
		int param_cnt;
    }st[501];

    struct constant_table {
        char type[100];
        char name[100];
        int valid;
    }ct[501];

	struct func_table {
		char params[100];
		char name[100];
		int valid;
	} funct[501];

	char get_identifier_type(char* matchstr) {
		for(int i = 0; i < 501; i++) {
			if(strcmp(st[i].name, matchstr) == 0) {
				if(st[i].scope > cur_scope) {
					printf("LINE: %d ", yylineno);
					puts("ERROR: Undeclared Variable.");
					exit(0);
				}
				return st[i].type[0];
			}
		}
	}

	void insert_symbol_table_line(char *str1, int line)
	{
		for(int i = 0 ; i < 501 ; i++)
		{
			if(strcmp(st[i].name,str1)==0)
			{
				st[i].line_number = line;
			}
		}
	}

    int hash_function(char *str)
	{
		int value = 0;
		for(int i = 0 ; i < strlen(str) ; i++)
		{
			value = 10*value + (str[i] - 'A');
			value = value % 501;
			while(value < 0)
				value = value + 501;
		}
		return value;
	}
	int lookup_symbolTable(char *str)
	{
		int value = hash_function(str);
		if(st[value].valid == 0)
		{
			return 0;
		}
		else if(strcmp(st[value].name,str)==0)
		{
			return value;
		}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%501)
	    	{
	    		if(strcmp(st[i].name,str)==0)
	    		{
	    			return i;
	    		}
	    	}
	    	return 0;
	    }
	}
	int lookup_constantTable(char *str)
	{
		int value = hash_function(str);
		if(ct[value].valid == 0)
			return 0;
		else if(strcmp(ct[value].name,str)==0)
			return 1;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%501)
			{
				if(strcmp(ct[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}
	void insert_symbolTable(char *str1, char *str2)
	{
		if(lookup_symbolTable(str1))
		{
		    return;
	    }
		else
		{
			int value = hash_function(str1);
			if(st[value].valid == 0)
			{
				strcpy(st[value].name,str1);
				strcpy(st[value].Class, str2);
				st[value].valid = strlen(str1);
				st[value].scope = INT_MAX;
				insert_symbol_table_line(str1, yylineno);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%501)
			{
				if(st[i].valid == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(st[pos].name,str1);
			strcpy(st[pos].Class,str2);
			st[pos].valid = strlen(str1);
			st[pos].scope = INT_MAX;
		}
	}

	void insert_symbol_table_scope(char* str, int scope) {
		int pos = lookup_symbolTable(str);

		if(pos && st[pos].scope != INT_MAX) {
			int val = hash_function(str);

			for(int i = val, loopCnt = 0; loopCnt < 502; i = (i + 1) % 501, loopCnt++) {
				
				if(st[i].valid == 1) {
					if(st[i].scope == scope && strcmp(str, st[i].name) == 0) {
						printf("LINE: %d ", yylineno);
						puts("ERROR: DUPLICATE declaration");
						exit(-1);
						return;
					}
				}
			}
			for(int i = val + 1; i != val; i = (i + 1) % 501) {
				if(st[i].valid == 0) {
					strcpy(st[i].name,str);
					strcpy(st[i].Class, str);
					st[i].valid = strlen(str);
					st[i].scope = scope;
					st[i].line_number = yylineno;
					return;
				}
			}
		} else {
			for(int i = 0; i < 501; i++) {
				if(strcmp(st[i].name, str) == 0) {
					st[i].scope = scope;
					return;
				}
			}
		}
	}
	int remove_scope(int scope) {
		for(int i = 0; i < 501; i++) {
			if(st[i].valid && st[i].scope == scope) {
				st[i].scope = INT_MAX;
			}
		}
	}

	void insert_func_table(char* func) {
		int val = hash_function(func);
		if(funct[val].valid == 0) {
			strcpy(funct[val].name, func);
			funct[val].valid = strlen(func);
		} else {
			printf("LINE: %d ", yylineno);
			puts("ERROR: Duplicate Function declaration");
		}
	}

	void insert_symbol_table_params_cnt(char* str, int param_count) {
		int pos = lookup_symbolTable(str);
		st[pos].param_cnt = param_count;
	}
	int verify_funccall_cnt(char* str, int cnt) { 
		int pos = lookup_symbolTable(str);
		return st[pos].param_cnt == cnt;
	}

	void insert_arg_type(char* type, char* func, int pos) {
		int posi = lookup_symbolTable(func);
		funct[posi].params[pos] = type[0];	
		if(type[0] == 'v') {
			puts("ERROR: void type parameter!");
			exit(-1);
		}	
	}


	int check_arg_type(int typid, char* func, int pos) {
		int posi = lookup_symbolTable(func);
		if(posi == 0 || funct[posi].valid == 0) {
			printf("LINE: %d ", yylineno);
			puts("ERROR: Function Not Declared");
			exit(-1);
		}
		if(typid == 5 && funct[posi].params[pos] == 'i') {

		} else if(typid == 6 && funct[posi].params[pos] == 'c') {

		}  else {
			printf("LINE: %d ", yylineno);
			puts("ERROR: Arguments mismatch");
			exit(-1);
		}
	}

	void insert_symbol_table_type(char *str1, char *str2)
	{
		for(int i = 0 ; i < 501 ; i++)
		{
			if(strcmp(st[i].name,str1)==0)
			{	
				strcpy(st[i].type,str2);
			}
		}
    }

	void insert_symbol_table_value(char *str1, char *str2)
	{
		for(int i = 0 ; i < 501 ; i++)
		{
			if(strcmp(st[i].name,str1)==0)
			{
				strcpy(st[i].value,str2);
			}
		}
	}

	
	void insert_constantsTable(char *str1, char *str2)
	{
		if(lookup_constantTable(str1))
			return;
		else
		{
			int value = hash_function(str1);
			if(ct[value].valid == 0)
			{
				strcpy(ct[value].name,str1);
				strcpy(ct[value].type,str2);
				ct[value].valid = strlen(str1);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%501)
			{
				if(ct[i].valid == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ct[pos].name,str1);
			strcpy(ct[pos].type,str2);
			ct[pos].valid = strlen(str1);
		}
	}

	void print_symbol_table()
	{
		printf("%10s | %15s | %10s | %10s | %10s  \n","SYMBOL", "CLASS", "TYPE","VALUE", "LINE NO");
		for(int i=0;i<81;i++) {
			printf("-");
		}
		printf("\n");
		for(int i = 0 ; i < 501 ; i++)
		{
			if(st[i].valid == 0)
			{
				continue;
			}
			printf("%10s | %15s | %10s | %10s | %10d  \n",st[i].name, st[i].Class, st[i].type, st[i].value, st[i].line_number);
		}
    }

	void print_func_table() {
		printf("%10s | %10s | %10s \n","Name", "Parameters Count", "PARAM TYPE");
		for(int i=0;i<61;i++) {
			printf("-");
		}
		puts("");
		for(int i = 0; i < 501; i++) {
			if(funct[i].valid) {
				printf("%10s | %d ", funct[i].name, st[i].param_cnt);
				printf("%17s", " ");
				for(int j = 0; j < st[i].param_cnt; j++) {
					printf(" %c, ", funct[i].params[j]);
				}
				puts("");
			}
		}

	}

	void print_constant_table()
	{
		printf("%10s | %15s\n","NAME", "TYPE");
		for(int i=0;i<81;i++) {
			printf("-");
		}
		printf("\n");
		for(int i = 0 ; i < 501 ; i++)
		{
			if(ct[i].valid == 0)
				continue;

			printf("%10s | %15s\n",ct[i].name, ct[i].type);
		}
	}

    int cbracketsopen = 0;
    int cbracketsclose = 0;
    int bbracketsopen = 0;
    int bbracketsclose = 0;
    int fbracketsopen = 0;
    int fbracketsclose = 0;

	char Match_str[20];
	char Match_type[20];
	char curval[20];
	char cur_identifier[20];
	char cur_function[20];
	char cur_type[20];

#line 1029 "lex.yy.c"
#line 1030 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 383 "scanner.l"



#line 1251 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 257 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 585 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 386 "scanner.l"
{yylineno++;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 387 "scanner.l"
{
    for(int i = 0; i < strlen(yytext); i++) {
        if(yytext[i] == '\n') yylineno++;
    }
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 392 "scanner.l"
;
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 393 "scanner.l"
{
     for(int i = 0; i < strlen(yytext); i++) {
        if(yytext[i] == '\n') yylineno++;
    }
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 398 "scanner.l"
{printf("%s is a header declaration\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 401 "scanner.l"
{ return(':'); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 402 "scanner.l"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 404 "scanner.l"
{
    // printf("%s is a keyword\n", yytext);
	if(strcmp(yytext, "auto") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(AUTO);
	}
	else if(strcmp(yytext, "double") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(DOUBLE);
	}
	else if(strcmp(yytext, "int") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(INT);
	}
	else if(strcmp(yytext, "struct") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(STRUCT);
	}
	else if(strcmp(yytext, "break") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(BREAK);
	}
	else if(strcmp(yytext, "else") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(ELSE);
	}
	else if(strcmp(yytext, "long") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(LONG);
	}
	else if(strcmp(yytext, "switch") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(SWITCH);
	}
	else if(strcmp(yytext, "case") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(CASE);
	}
	else if(strcmp(yytext, "enum") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(ENUM);
	}
	else if(strcmp(yytext, "register") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(REG);
	}
	else if(strcmp(yytext, "typedef") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(TYPEDEF);
	}
	else if(strcmp(yytext, "char") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(CHAR);
	}
	else if(strcmp(yytext, "extern") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(EXTERN);
	}
	else if(strcmp(yytext, "return") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(RETURN);
	}
	else if(strcmp(yytext, "union") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(UNION);
	}
	else if(strcmp(yytext, "continue") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(CONTINUE);
	}
	else if(strcmp(yytext, "for") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(FOR);
	}
	else if(strcmp(yytext, "signed") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(SIGNED);
	}
	else if(strcmp(yytext, "void") == 0){
		strcpy(Match_type, yytext);
		insert_symbolTable(yytext, "KEYWORD");
		return(VOID);
	}
	else if(strcmp(yytext, "do") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(DO);
	}
	else if(strcmp(yytext, "if") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(IF);
	}
	else if(strcmp(yytext, "static") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(STATIC);
	}
	else if(strcmp(yytext, "while") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(WHILE);
	}
	else if(strcmp(yytext, "default") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(DEFAULT);
	}
	else if(strcmp(yytext, "goto") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(GOTO);
	}
	else if(strcmp(yytext, "volatile") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(VOLATILE);
	}
	else if(strcmp(yytext, "const") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(CONST);
	}
	else if(strcmp(yytext, "float") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(FLOAT);
	}
	else if(strcmp(yytext, "short") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(SHORT);
	}
	else if(strcmp(yytext, "unsigned") == 0){
		insert_symbolTable(yytext, "KEYWORD");
		return(UNSIGNED);
	}
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 543 "scanner.l"
{
  printf("In LineNo: %d, ERROR: Invalid Identifier : %s\n", yylineno, yytext);  exit(1);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 546 "scanner.l"
{
    printf("In LineNo: %d, ERROR: String usage error in %s\n", yylineno, yytext);  exit(1);
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 550 "scanner.l"
{
    printf("In LineNo: %d, ERROR: Character usage error: %s\n", yylineno, yytext);  exit(1);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 554 "scanner.l"
{
    // printf("%s is a identifier\n", yytext);
	strcpy(Match_str, yytext);
	strcpy(cur_identifier, yytext);
	insert_symbolTable(yytext, "Identifier");
	return(IDENTIFIER);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 562 "scanner.l"
{
    // printf("%s is a constant\n", yytext);
	strcpy(curval, yytext);
	// insert_constantsTable(yytext, "Constant");
	for(int i = 0; i < strlen(yytext); i++) {
        if(yytext[i] == '\n') yylineno++;
    }
	insert_constantsTable(yytext, "NUMERICAL CONSTANT");
	return(NUM_CONSTANT);
    }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 573 "scanner.l"
{
    // printf("%s is a constant\n", yytext);
	// insert_constantsTable(yytext, "Constant");
	strcpy(curval, yytext);
	for(int i = 0; i < strlen(yytext); i++) {
        if(yytext[i] == '\n') yylineno++;
    }
	insert_constantsTable(yytext, "CHAR CONSTANT");
	return(CHAR_CONSTANT);
    }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 584 "scanner.l"
{
    // printf("%s is a constant\n", yytext);
	// insert_constantsTable(yytext, "Constant");
	strcpy(curval, yytext);
	for(int i = 0; i < strlen(yytext); i++) {
        if(yytext[i] == '\n') yylineno++;
    }
	insert_constantsTable(yytext, "STRING CONSTANT");
	return(STRING_CONSTANT);
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 596 "scanner.l"
{
    // printf("%s is a special symbol\n", yytext);
	
	if(yytext[0] == ';') { return(';'); }
	else
	if(yytext[0] == ',') { return(','); }
	else	
    if(yytext[0] == '{'){
        fbracketsopen++;   
		return('{'); 
    }
    else if(yytext[0] == '}'){
        fbracketsclose++;
		return('}');
    }
    else if(yytext[0] == '('){
        cbracketsopen++;
		return('(');
    }
    else if(yytext[0] == ')'){
        cbracketsclose++;
		 return(')');
    }
    else if(yytext[0] == '['){
        bbracketsopen++;
		return('[');
    }
    else if(yytext[0] == ']'){
        bbracketsclose++;
		return(']'); 
    }
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 630 "scanner.l"
{
    // printf("%s is an operator\n", yytext);
	if(strcmp(yytext, "++") == 0) return increment;
	else if(strcmp(yytext, "--") == 0) return decrement;
	else if(strcmp(yytext, "<<") == 0) return leftshift;
	else if(strcmp(yytext, ">>") == 0) return rightshift;
	else if(strcmp(yytext, "<=") == 0) return lessthanAssignment;
	else if(strcmp(yytext, "<") == 0) return lessthan;
	else if(strcmp(yytext, ">=") == 0) return greaterthanAssignment;
	else if(strcmp(yytext, ">") == 0) return greaterthan;
	else if(strcmp(yytext, "==") == 0) return equality;
	else if(strcmp(yytext, "!=") == 0) return inequality;
	else if(strcmp(yytext, "&&") == 0) return and;
	else if(strcmp(yytext, "||") == 0) return or;
	else if(strcmp(yytext, "^") == 0) return xor;
	else if(strcmp(yytext, "*=") == 0) return multiplicationAssignment;
	else if(strcmp(yytext, "/=") == 0) return divisionAssignment;
	else if(strcmp(yytext, "%=") == 0) return moduloAssignment;
	else if(strcmp(yytext, "+=") == 0) return additionAssignment;
	else if(strcmp(yytext, "-=") == 0) return subtractionAssignment;
	else if(strcmp(yytext, "<<=") == 0) return leftshiftAssignment;
	else if(strcmp(yytext, ">>=") == 0) return rightshiftAssignment;
	else if(strcmp(yytext, "&=") == 0) return andAssignment;
	else if(strcmp(yytext, "|=") == 0) return orAssignment;
	else if(strcmp(yytext, "&") == 0) return bitAnd;
	else if(strcmp(yytext, "!") == 0) return not;
	else if(strcmp(yytext, "~") == 0) return negation;
	else if(strcmp(yytext, "|") == 0) return bitOr;
	else if(strcmp(yytext, "-") == 0) return subtract;
	else if(strcmp(yytext, "+") == 0) return add;
	else if(strcmp(yytext, "*") == 0) return multiplication;
	else if(strcmp(yytext, "/") == 0) return divide;
	else if(strcmp(yytext, "%") == 0) return modulo;
	else if(strcmp(yytext, "=") == 0) return assignment;  
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 666 "scanner.l"
ECHO;
	YY_BREAK
#line 1653 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 257 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 257 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 256);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 666 "scanner.l"




int yywrap(){
    return(1);
}

